// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8yhiRgI3Dx_YkAwNvbir5V0iRFkvwMqQ',
    appId: '1:88283643891:web:31ae6ff0bfa90c9d8b5c86',
    messagingSenderId: '88283643891',
    projectId: 'housekeep-560cf',
    authDomain: 'housekeep-560cf.firebaseapp.com',
    storageBucket: 'housekeep-560cf.firebasestorage.app',
    measurementId: 'G-WB9NM96RZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLj3ELivOHiF4lETTV8m7NfCEOcnUexiY',
    appId: '1:88283643891:android:1af682a3a5c3067f8b5c86',
    messagingSenderId: '88283643891',
    projectId: 'housekeep-560cf',
    storageBucket: 'housekeep-560cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0w_JCReRUESP1s1zyMiSAxb-ZpOiBJ3Y',
    appId: '1:88283643891:ios:e532d287f97c14228b5c86',
    messagingSenderId: '88283643891',
    projectId: 'housekeep-560cf',
    storageBucket: 'housekeep-560cf.firebasestorage.app',
    iosBundleId: 'com.example.housekeep',
  );
}
